# Generated by Django 4.1 on 2023-02-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
    ]
