# Generated by Django 4.1 on 2023-02-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0002_alter_publicacion_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='texto',
            field=models.TextField(max_length=700),
        ),
    ]
