# Generated by Django 4.1 on 2023-02-09 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_alter_publicacion_texto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['fecha_creacion']},
        ),
    ]
