# Generated by Django 3.2 on 2023-04-18 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0006_alter_comentario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={},
        ),
    ]
