# Generated by Django 3.2 on 2023-05-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0007_alter_comentario_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='texto',
            field=models.TextField(max_length=1000),
        ),
    ]
