# Generated by Django 3.2 on 2023-06-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0009_alter_publicacion_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='texto',
            field=models.TextField(max_length=1000),
        ),
    ]
